"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import Link from "next/link";
import * as THREE from "three";
import { OrbitControls } from "three/examples/jsm/controls/OrbitControls.js";
import type { Exoplanet, ExoplanetResponse } from "../lib/exoplanets";
import { COLOR_METRIC_LABELS, DEFAULT_MAP_CONFIG, type ColorMetric, type MapConfig } from "../lib/map-config";

const scenes = [
  { eyebrow: "01 / CELESTIAL GLOBE", title: "Generate a live map of confirmed worlds.", text: "Use real sky coordinates from the NASA Exoplanet Archive, then color the map by one measured field at a time." },
  { eyebrow: "02 / PLANETARY SCALE", title: "Compare measured planet sizes.", text: "Planet markers grow with recorded radius. Missing measurements stay neutral and visible in the legend." },
  { eyebrow: "03 / DETECTION METHODS", title: "See how each world was found.", text: "Color the globe by detection method and compare the observational record across the sky." },
  { eyebrow: "04 / SYSTEM DETAIL", title: "Inspect one system at a time.", text: "Select any mapped world or use the index to read its recorded facts and host star." },
];

const methodColors: Record<string, number> = { Transit: 0x4da3ff, "Radial Velocity": 0xf0a34a, Imaging: 0x8c9eff, Microlensing: 0x55c7c4 };

function format(value: number | null, unit: string) { return value === null ? "Not recorded" : `${value.toLocaleString(undefined, { maximumFractionDigits: 2 })} ${unit}`; }

function getMetricValue(planet: Exoplanet, metric: ColorMetric): number | string | null { if (metric === "method") return planet.discoveryMethod; return planet[metric]; }

function markerColor(planet: Exoplanet, metric: ColorMetric, planets: Exoplanet[]): number {
  const value = getMetricValue(planet, metric);
  if (metric === "method") return methodColors[String(value)] ?? 0x7e8b9c;
  if (typeof value !== "number") return 0x657386;
  const values = planets.map((item) => getMetricValue(item, metric)).filter((item): item is number => typeof item === "number");
  const min = Math.min(...values); const max = Math.max(...values); const t = max === min ? 0.5 : (value - min) / (max - min);
  return new THREE.Color().setHSL(0.58 - t * 0.47, 0.72, 0.56).getHex();
}

function coordinates(planet: Exoplanet): THREE.Vector3 | null {
  if (planet.rightAscension === null || planet.declination === null) return null;
  const ra = THREE.MathUtils.degToRad(planet.rightAscension); const dec = THREE.MathUtils.degToRad(planet.declination);
  return new THREE.Vector3(Math.cos(dec) * Math.cos(ra), Math.sin(dec), Math.cos(dec) * Math.sin(ra));
}

function CelestialGlobe({ planets, config, selected, onSelect, onHover }: { planets: Exoplanet[]; config: MapConfig; selected: Exoplanet | null; onSelect: (planet: Exoplanet) => void; onHover: (planet: Exoplanet | null) => void }) {
  const mount = useRef<HTMLDivElement>(null); const state = useRef({ planets, config, selected, onSelect, onHover });
  useEffect(() => { state.current = { planets, config, selected, onSelect, onHover }; }, [planets, config, selected, onSelect, onHover]);
  useEffect(() => {
    if (!mount.current) return; const host = mount.current; const renderer = new THREE.WebGLRenderer({ antialias: true, alpha: true }); renderer.setPixelRatio(Math.min(window.devicePixelRatio, 2)); renderer.setClearColor(0x000000, 0); host.appendChild(renderer.domElement);
    const camera = new THREE.PerspectiveCamera(35, 1, 0.1, 100); camera.position.set(0, 0, 8.4); const scene = new THREE.Scene(); const globe = new THREE.Group(); scene.add(globe);
    const sphere = new THREE.Mesh(new THREE.SphereGeometry(3.2, 32, 24), new THREE.MeshBasicMaterial({ color: 0x122031, transparent: true, opacity: 0.26, wireframe: true })); globe.add(sphere);
    const equator = new THREE.Mesh(new THREE.TorusGeometry(3.2, 0.008, 4, 96), new THREE.MeshBasicMaterial({ color: 0x4b7194, transparent: true, opacity: 0.5 })); globe.add(equator);
    const markers = new THREE.Group(); globe.add(markers); const raycaster = new THREE.Raycaster(); const pointer = new THREE.Vector2(); let hovered: Exoplanet | null = null;
    const rebuild = () => { markers.clear(); const current = state.current; current.planets.forEach((planet) => { const position = coordinates(planet); if (!position) return; const radius = current.config.colorMetric === "radius" && planet.radius !== null ? 0.055 + Math.min(planet.radius, 5) * 0.018 : 0.075; const material = new THREE.MeshBasicMaterial({ color: markerColor(planet, current.config.colorMetric, current.planets), transparent: true, opacity: 0.9 }); const marker = new THREE.Mesh(new THREE.SphereGeometry(radius, 10, 10), material); marker.position.copy(position.multiplyScalar(3.25)); marker.userData.planet = planet; markers.add(marker); }); };
    rebuild(); const controls = new OrbitControls(camera, renderer.domElement); controls.enablePan = false; controls.enableDamping = true; controls.dampingFactor = 0.08; controls.minDistance = 4.8; controls.maxDistance = 13; controls.autoRotate = state.current.config.autoRotate; controls.autoRotateSpeed = 0.65; controls.target.set(0, 0, 0);
    const resize = () => { const rect = host.getBoundingClientRect(); renderer.setSize(rect.width, rect.height, false); camera.aspect = rect.width / Math.max(rect.height, 1); camera.updateProjectionMatrix(); }; const pointerMove = (event: PointerEvent) => { const rect = renderer.domElement.getBoundingClientRect(); pointer.x = ((event.clientX - rect.left) / rect.width) * 2 - 1; pointer.y = -((event.clientY - rect.top) / rect.height) * 2 + 1; raycaster.setFromCamera(pointer, camera); const hit = raycaster.intersectObjects(markers.children); hovered = hit[0]?.object.userData.planet ?? null; state.current.onHover(hovered); renderer.domElement.style.cursor = hovered ? "pointer" : "grab"; }; const click = () => { if (hovered) state.current.onSelect(hovered); };
    renderer.domElement.addEventListener("pointermove", pointerMove); renderer.domElement.addEventListener("click", click); const observer = new ResizeObserver(resize); observer.observe(host); resize(); let animation = 0; const tick = () => { const current = state.current; controls.autoRotate = current.config.autoRotate; markers.children.forEach((marker) => { const planet = marker.userData.planet as Exoplanet; const selectedState = planet.id === current.selected?.id; const hoverState = planet.id === hovered?.id; const material = marker.material as THREE.MeshBasicMaterial; material.color.setHex(selectedState ? 0xffffff : hoverState ? 0xd8f5ff : markerColor(planet, current.config.colorMetric, current.planets)); material.opacity = selectedState || hoverState ? 1 : 0.86; }); controls.update(); renderer.render(scene, camera); animation = requestAnimationFrame(tick); }; animation = requestAnimationFrame(tick);
    return () => { cancelAnimationFrame(animation); observer.disconnect(); controls.dispose(); renderer.domElement.removeEventListener("pointermove", pointerMove); renderer.domElement.removeEventListener("click", click); renderer.dispose(); host.removeChild(renderer.domElement); };
  }, [planets, config]);
  return <div ref={mount} className="globe-canvas" role="img" aria-label="Rotatable celestial globe showing exoplanets at their recorded sky coordinates" />;
}

export default function Home() {
  const [data, setData] = useState<ExoplanetResponse | null>(null); const [scene, setScene] = useState(0); const [selected, setSelected] = useState<Exoplanet | null>(null); const [hovered, setHovered] = useState<Exoplanet | null>(null); const [draft, setDraft] = useState<MapConfig>(DEFAULT_MAP_CONFIG); const [config, setConfig] = useState<MapConfig>(DEFAULT_MAP_CONFIG);
  useEffect(() => { fetch("/api/exoplanets").then((response) => response.json()).then((payload: ExoplanetResponse) => { setData(payload); setSelected(payload.items[0] ?? null); }).catch(() => setData(null)); }, []);
  const planets = useMemo(() => data?.items ?? [], [data]); const methods = useMemo(() => ["All methods", ...Array.from(new Set(planets.map((planet) => planet.discoveryMethod))).sort()], [planets]); const filtered = useMemo(() => planets.filter((planet) => (config.discoveryMethod === "All methods" || planet.discoveryMethod === config.discoveryMethod) && (planet.discoveryYear === null || (planet.discoveryYear >= config.discoveryYearRange[0] && planet.discoveryYear <= config.discoveryYearRange[1]))), [planets, config]); const mapped = useMemo(() => filtered.filter((planet) => coordinates(planet)), [filtered]); const activeSelected = selected && filtered.some((planet) => planet.id === selected.id) ? selected : filtered[0] ?? null; const activeScene = scenes[scene]; const mappedIds = new Set(mapped.map((planet) => planet.id));
  const applyConfig = () => { setConfig({ ...draft, discoveryYearRange: [...draft.discoveryYearRange] as [number, number] }); if (activeSelected && !filtered.some((planet) => planet.id === activeSelected.id)) setSelected(filtered[0] ?? null); }; const resetConfig = () => { setDraft(DEFAULT_MAP_CONFIG); setConfig(DEFAULT_MAP_CONFIG); }; const updateYear = (index: 0 | 1, value: number) => { const next: [number, number] = [...draft.discoveryYearRange] as [number, number]; next[index] = value; if (next[0] > next[1]) next[index === 0 ? 1 : 0] = value; setDraft({ ...draft, discoveryYearRange: next }); };
  const metricLabel = COLOR_METRIC_LABELS[config.colorMetric]; const mappedLabel = `${mapped.length} of ${filtered.length} records mapped`; return <main className="atlas-shell"><header className="topbar"><Link className="brand" href="/" aria-label="Astraea Atlas home"><span className="brand-mark">✦</span><span>ASTRAEA <em>ATLAS</em></span></Link><div className="topbar-note"><span className={`status-dot ${data?.source === "fallback" ? "stale" : ""}`} />{data ? data.source === "live" ? "LIVE ARCHIVE" : "OFFLINE SET" : "CONNECTING"}<span className="topbar-divider" />NASA EXOPLANET ARCHIVE</div></header>
    <section className="hero"><div className="story-copy"><div className="mission-line"><span className="live-pulse" /> ARCHIVE TELEMETRY <strong>{data?.source === "fallback" ? "OFFLINE" : data ? "NOMINAL" : "CONNECTING"}</strong></div><p className="kicker">{activeScene.eyebrow}</p><h1>{activeScene.title}</h1><p className="lede">{activeScene.text}</p><div className="data-greeting" aria-label="Current map summary"><div><strong>{mapped.length || "—"}</strong><span>MAPPED WORLDS</span></div><div><strong>{filtered.length || "—"}</strong><span>FILTERED RECORDS</span></div><div><strong>{metricLabel}</strong><span>COLOR FIELD</span></div></div><div className="scene-nav" aria-label="Story scenes">{scenes.map((item, index) => <button key={item.eyebrow} className={index === scene ? "active" : ""} onClick={() => setScene(index)} aria-label={`Scene ${index + 1}: ${item.title}`} aria-current={index === scene ? "step" : undefined}><span>0{index + 1}</span>{item.title}</button>)}</div></div><div className="hero-visual"><div className="visual-caption"><span>GENERATED CELESTIAL GLOBE</span><span>{mappedLabel}</span></div><CelestialGlobe planets={filtered} config={config} selected={activeSelected} onSelect={setSelected} onHover={setHovered} /><div className="globe-overlay" aria-live="polite">{hovered ? <><strong>{hovered.name}</strong><span>{hovered.hostStar}</span></> : <><strong>DRAG TO ROTATE</strong><span>Scroll to zoom · click a world to inspect</span></>}</div><div className="legend"><span><i className="legend-gradient" />{metricLabel}</span><span><i className="legend-dot missing" />Not recorded</span><span>{mapped.length} mapped</span></div></div></section>
    <section className="generator" aria-label="Generate map controls"><div className="generator-heading"><p className="kicker">MAP GENERATOR</p><span>Control-generated · local view</span></div><div className="generator-controls"><div className="control-group"><label htmlFor="method">Detection method</label><select id="method" value={draft.discoveryMethod} onChange={(event) => setDraft({ ...draft, discoveryMethod: event.target.value })}>{methods.map((item) => <option key={item}>{item}</option>)}</select></div><div className="control-group"><label htmlFor="metric">Color by</label><select id="metric" value={draft.colorMetric} onChange={(event) => setDraft({ ...draft, colorMetric: event.target.value as ColorMetric })}>{Object.entries(COLOR_METRIC_LABELS).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></div><div className="control-group year-pair"><label>Discovery year range <strong>{draft.discoveryYearRange[0]}—{draft.discoveryYearRange[1]}</strong></label><div className="range-pair"><input aria-label="Earliest discovery year" type="range" min="1990" max="2025" value={draft.discoveryYearRange[0]} onChange={(event) => updateYear(0, Number(event.target.value))} /><input aria-label="Latest discovery year" type="range" min="1990" max="2025" value={draft.discoveryYearRange[1]} onChange={(event) => updateYear(1, Number(event.target.value))} /></div></div><label className="rotate-toggle"><input type="checkbox" checked={draft.autoRotate} onChange={(event) => setDraft({ ...draft, autoRotate: event.target.checked })} /> Auto-rotate</label><button className="generate-button" onClick={applyConfig}>Generate map</button><button className="reset-button" onClick={resetConfig}>Reset</button></div><p className="generator-note">Position uses recorded right ascension and declination. Records without valid coordinates remain in the index but are not placed on the globe.</p></section>
    <section className="detail-grid"><div className="planet-index"><div className="section-heading"><p className="kicker">THE INDEX</p><span>{filtered.length.toString().padStart(2, "0")} / {planets.length.toString().padStart(2, "0")}</span></div><div className="planet-list" role="listbox" aria-label="Planets in the current map">{filtered.slice(0, 16).map((planet) => <button key={planet.id} className={activeSelected?.id === planet.id ? "planet-row selected" : "planet-row"} onClick={() => setSelected(planet)} role="option" aria-selected={activeSelected?.id === planet.id}><span className={`row-orb ${mappedIds.has(planet.id) ? "" : "unmapped"}`} style={{ background: mappedIds.has(planet.id) ? `#${markerColor(planet, config.colorMetric, filtered).toString(16)}` : undefined }} /><span><strong>{planet.name}</strong><small>{planet.hostStar}{mappedIds.has(planet.id) ? "" : " · not mapped"}</small></span><time>{planet.discoveryYear ?? "—"}</time></button>)}</div></div><aside className="detail-card" aria-live="polite"><div className="card-top"><p className="kicker">SELECTED WORLD</p><span className="card-index">{activeSelected ? activeSelected.name : "—"}</span></div>{activeSelected ? <><h2>{activeSelected.name}</h2><p className="host">orbiting <strong>{activeSelected.hostStar}</strong>{mappedIds.has(activeSelected.id) ? " · mapped" : " · coordinate unavailable"}</p><dl className="facts"><div><dt>Discovery</dt><dd>{activeSelected.discoveryYear ?? "Not recorded"}</dd></div><div><dt>Method</dt><dd>{activeSelected.discoveryMethod}</dd></div><div><dt>Orbital period</dt><dd>{format(activeSelected.orbitalPeriod, "days")}</dd></div><div><dt>Radius</dt><dd>{format(activeSelected.radius, "R⊕")}</dd></div><div><dt>Mass</dt><dd>{format(activeSelected.mass, "M⊕")}</dd></div><div><dt>Distance</dt><dd>{format(activeSelected.distance, "pc")}</dd></div></dl><p className="fact-note">Measured archive values only. Color is a visual encoding of {metricLabel.toLowerCase()}; it is not a scientific score.</p></> : <p>Select a world from the index.</p>}</aside></section>
    <footer><span>ASTRAEA ATLAS · NASA EXOPLANET ARCHIVE</span><span>{data?.fetchedAt ? `DATA SYNC ${new Date(data.fetchedAt).toLocaleDateString()}` : "DATA SYNC —"}</span></footer>{data?.stale && <div className="offline-banner" role="status">{data.message} Coordinate view is unavailable for offline records.</div>}</main>;
}
